spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

strict:
  google:
    client-id: ${STRICT_GOOGLE_CLIENT_ID}
